### ISSUE TITLE
Breaks in IE9 when devtools are opened before the page is loaded

### ISSUE THREAD

**Issue by jakub-g** [dharFr/badgee#65]
In IE9, normally `console` is undefined, and things work well in such scenario, but when you open devtools before loading the page, it becomes defined (known quirk of IE...), and this breaks things somehow

![image](https://user-images.githubusercontent.com/1437027/45043057-7cb51980-b06c-11e8-9e39-f910dcab38d1.png)

![image](https://user-images.githubusercontent.com/1437027/45042944-39f34180-b06c-11e8-9501-1c17d371761c.png)

Based on quick debugging, it's probably this line (that gets compiled to `.bind.apply`) that is mentioned in the first error:
https://github.com/dharFr/badgee/blob/master/src/badgee.js#L50
 (not sure what's the exact issue though, didn't dig too much into it yet).

**Comment by dharFr** [comment]
Weird, that case was supposed to be handled already (see https://github.com/dharFr/badgee/blob/master/src/badgee.js#L94-L103). 
I'll have a look.

**Comment by jakub-g** [comment]
Ah yeah indeed, it's an object and not a method
`typeof console.log == "object" // true`
<insert IE meme here>
